name: Fetch Data from NocoDB

on:
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Fetch data from NocoDB
      run: datasite.js
      env:
        XC_AUTH_TOKEN: ${{ secrets.XC_AUTH_TOKEN }}
